language: python

python:
  - 3.6.6

services: postgresql

env:
  - DJANGO=2.1.1

before_install:
  - export DJANGO_SETTINGS_MODULE=superPotato.settings
  - export PYTHONPATH=$HOME/builds/guilehm/super-potato
  - export PIP_USE_MIRRORS=true

install:
  - pip install pipenv
  - pipenv install
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - isort --check-only
  - flake8
