# Generated by Django 2.1.1 on 2018-09-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
