# Generated by Django 2.1.1 on 2018-09-14 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transfer_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='register.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='register.Entity')),
                ('health_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='register.HealthPlan')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='register.Entity')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='attendance.Service')),
            ],
            options={
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='attendance.Specialty'),
        ),
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together={('name', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'health_plan')},
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('name', 'specialty')},
        ),
    ]
