# Generated by Django 2.1.1 on 2018-09-14 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='entity',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='register.Entity'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='attendance.Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='added_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='entity',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='register.Entity'),
        ),
        migrations.AddField(
            model_name='service',
            name='health_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='register.HealthPlan'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='entity',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='register.Entity'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='attendance.Specialty'),
        ),
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together={('name', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'health_plan')},
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('name', 'specialty')},
        ),
    ]
