# Generated by Django 2.1.1 on 2018-09-14 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='entity',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='register.Entity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='health_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='register.HealthPlan'),
        ),
    ]
