# Generated by Django 2.1.1 on 2018-09-14 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('attendance', '0002_auto_20180914_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='entity',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='register.Entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialty',
            name='entity',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='register.Entity'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('name', 'specialty')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'health_plan')},
        ),
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together={('name', 'service')},
        ),
    ]
